function mainmenu() {
    location.href = "index.html";
};
function back() {
    history.go(-1)
};

var dispUrl = sessionStorage.getItem("imgUrl")
document.getElementById("bgImg").setAttribute("src", dispUrl)
document.getElementById("dispImg").setAttribute("src", dispUrl)

function logPic(id,name,author,text) {
    var o = new Object();
    o.id = id;
    o.name = name;
    o.author = author;
    o.text = text;
    return o;
}

var a1 = logPic('a1','Anti-theft window','Dong Jiayi','This photo was taken during the epidemic isolation. The unified anti-theft window frame in the community was used as a shelf to store some of the owner daily necessities .In the case of being closed at home, the way of communication between people is limited, and the window becomes the only channel to observe other people living habits or imagine the owner daily life through the details by the window. Upholding curiosity and imagination, perhaps the loneliness of isolation can be lightened somewhat.')
var a2 = logPic('a2','Separator','Dong Jiayi','This photo was taken before Christmas, when there were not many people on the street due to the weather, the lights were dim, and there was a window There are many people laughing or chatting under the warm light in the bar. The window is a separator here, separating the outside world from the inside, isolating the light and temperature, leaving only the connected sense of vision, the five senses of the window inside and outside It becomes two wholes under limited circumstances, which brings people completely different feelings.')
var a3 = logPic('a3','Old bungalow','Jinhuijie','The collision of trendy and retro, fashion and nostalgia creates the unique style of Wukang Road architecture. Through the windows of the old bungalow, we can see the modern The aborigines still living in it learned about their living conditions. In the afternoon of spring, the grandma standing on the window sill in avant-garde clothes watched silently the tourists who stopped by, with a smile on her face. This kind interaction is undoubtedly becoming more and more popular. The street of Wukang Road, where Internet celebrities check in, adds a bit of humanistic feelings.')
var a4 = logPic('a4','Old','Li Siquan','The old windows, the blurred glass, and the rusty writing on the mailbox are slowly revealing their own stories.')
var a5 = logPic('a5','lock','Li Siquan','The number of locks on this door fluctuates. Sometimes heavy chains and locks keep me out, and sometimes these The locks were magically all unlocked, and the darkness in the half-closed door called me quietly. I have never entered the distant world behind this dark green window.')
var a6 = logPic('a6','Fishing Village','Mao Weizhe','Italian Cinque Terre. The corner of the square is very beautiful, the orange wall is illuminated by the setting sun, and the clothes hanging on the high clothesline, Any outfit is a work of art.')
var a7 = logPic('a7','Inside','Li Zhewen','This picture was taken in a residential building in Minhang District. For the understanding of the theme of "window", I think its content should focus on the A window or looking at things from a certain point of view. Therefore, what you see is the most important.')
var a8 = logPic('a8','corridor','Sun Jingqi','This picture was taken on the second floor of the Longmen Building of Shanghai Middle School in early autumn when the school year just started in 2021. The sun shines into the corridor through the windows on the west side of the second floor At that time, the trees were still lush and green, and the golden light was beating in this teaching building built in 1936. Outside the window was a great scene of hope, allowing us to look far away and feel the beauty of nature. The window is now, let us see Naturally. The reason why windows exist is that human beings have the desire to look from the inside out or from the outside to the inside. The inside is safe, and the window gives people the psychological needs to communicate with the outside world from the inside; at the same time, as Nietzsche said: "You When staring into the abyss, the abyss is also staring at you". This is a two-way process: from Hitchcock "Rear Window" to Bentham "Panoptic Prison". We see, also To be seen, fortunately, the view framed by the window allows us to give balance in the two-way relationship without having to "fly between heaven and earth".')
var a9 = logPic('a9','Life','Sun Jingqi', 'I only remember this photo at a certain noon, and I found a corner in a corner of the community looking at the next-door community. Under the cover of verdant trees, the hole opened There are some clothes hanging in the window with red painted edges. They are "seen", which also symbolizes the life that we open to others through the window and other media. At a glance, the ordinary window is life , mixing past and present.')
var a10 = logPic('a10','near','Tao Shengkai','-')
var a11 = logPic('a11','Jiao','Wang Jiahe', 'This photo was taken on a bright summer day at Duozhuoyu on Anfu Road. I think there can always be many interesting lights and shadows by the windows. There is sunshine outside the window, and the window is a particularly angular thing, so it can present a characteristic light. Light and shadow always attract me. I think photography and windows are actually quite similar. Before you look out of the window, you You never know the world outside the window. The scenery outside the window is always unknown and full of surprises. Before you press the shutter, you are never sure what kind of picture is in the viewfinder frame. I think this kind of unknown is The magic of photography.')
var a12 = logPic('a12','square','Jacky.Y','-')
var a13 = logPic('a13','circle','Jacky.Y','-')
var a14 = logPic('a14','Girl','Yao Yuxiao','taken at noon on Hengshan Road, Shanghai. The warm sun shines on the exterior wall of the repainted old bungalow, and the broken window has been repainted Illuminated under the spotlight. The simple potted plants on the air conditioner are still facing the sun, but I don’t know how much the girl in the window has turned white.')

var b1 = logPic('b1','Silent(Part 1)','Chen Yuwen','The long winter in New England is like a dream, and the speed of day and night is even more overwhelming. This small window happens to be Facing the stairway outside my room door, I always pass by it every time I go downstairs. The room is dark, but outside the window is often the scene of afterglow lingering on the branches and leaves. Every time I pass by, I can’t help but stop and look at it for a long time. The four-square window frame I live in such a painting, and I cannot help but want to pick up my phone to freeze this peaceful and romantic moment. The pixels of the photos are not high, and they are not carefully designed. Most of them are taken in a hurry with the phone before going to school, but the flowers are frozen. The falling snow and the dawn of dawn, this group of photos is like a train from autumn to spring. It reminds people of their state of mind at that time. It is a diary without words. I hope everyone can feel it after reading it. The beauty of the passage of time and the stillness of nature.')
var b2 = logPic('b2','Silence (Part 2)','Chen Yuwen','The long winter in New England is like a dream, and the speed of day and night is overwhelming. This small window happens to be Facing the stairway outside my room door, I always pass by it every time I go downstairs. The room is dark, but outside the window is often the scene of afterglow lingering on the branches and leaves. Every time I pass by, I can’t help but stop and look at it for a long time. The four-square window frame I live in such a painting, and I cannot help but want to pick up my phone to freeze this peaceful and romantic moment. The pixels of the photos are not high, and they are not carefully designed. Most of them are taken in a hurry with the phone before going to school, but the flowers are frozen. The falling snow and the dawn of dawn, this group of photos is like a train from autumn to spring. It reminds people of their state of mind at that time. It is a diary without words. I hope everyone can feel it after reading it. The beauty of the passage of time and the stillness of nature.')
var b3 = logPic('b3','Silence (Part 3)','Chen Yuwen','The long winter in New England is like a dream, and the speed of day and night is overwhelming. This small window happens to be Facing the stairway outside my room door, I always pass by it every time I go downstairs. The room is dark, but outside the window is often the scene of afterglow lingering on the branches and leaves. Every time I pass by, I can’t help but stop and look at it for a long time. The four-square window frame I live in such a painting, and I cannot help but want to pick up my phone to freeze this peaceful and romantic moment. The pixels of the photos are not high, and they are not carefully designed. Most of them are taken in a hurry with the phone before going to school, but the flowers are frozen. The falling snow and the dawn of dawn, this group of photos is like a train from autumn to spring. It reminds people of their state of mind at that time. It is a diary without words. I hope everyone can feel it after reading it. The beauty of the passage of time and the stillness of nature.')
var b4 = logPic('b4','Silent (Part 4)','Chen Yuwen','The long winter in New England is like a dream, and the speed of day and night is overwhelming. This small window happens to be Facing the stairway outside my room door, I always pass by it every time I go downstairs. The room is dark, but outside the window is often the scene of afterglow lingering on the branches and leaves. Every time I pass by, I can’t help but stop and look at it for a long time. The four-square window frame I live in such a painting, and I cannot help but want to pick up my phone to freeze this peaceful and romantic moment. The pixels of the photos are not high, and they are not carefully designed. Most of them are taken in a hurry with the phone before going to school, but the flowers are frozen. The falling snow and the dawn of dawn, this group of photos is like a train from autumn to spring. It reminds people of their state of mind at that time. It is a diary without words. I hope everyone can feel it after reading it. The beauty of the passage of time and the stillness of nature.')
var b5 = logPic('b5','Silent (Part 5)','Chen Yuwen','The long winter in New England is like a dream, and the speed of day and night changes is even more overwhelming. This small window happens to be Facing the stairway outside my room door, I always pass by it every time I go downstairs. The room is dark, but outside the window is often the scene of afterglow lingering on the branches and leaves. Every time I pass by, I can’t help but stop and look at it for a long time. The four-square window frame I live in such a painting, and I cannot help but want to pick up my phone to freeze this peaceful and romantic moment. The pixels of the photos are not high, and they are not carefully designed. Most of them are taken in a hurry with the phone before going to school, but the flowers are frozen. The falling snow and the dawn of dawn, this group of photos is like a train from autumn to spring. It reminds people of their state of mind at that time. It is a diary without words. I hope everyone can feel it after reading it. The beauty of the passage of time and the stillness of nature.')
var b6 = logPic('b6','Silence (Part 6)','Chen Yuwen','The long winter in New England is like a dream, and the speed of changing day and night is even more overwhelming. This small window happens to be Facing the stairway outside my room door, I always pass by it every time I go downstairs. The room is dark, but outside the window is often the scene of afterglow lingering on the branches and leaves. Every time I pass by, I can’t help but stop and look at it for a long time. The four-square window frame I live in such a painting, and I cannot help but want to pick up my phone to freeze this peaceful and romantic moment. The pixels of the photos are not high, and they are not carefully designed. Most of them are taken in a hurry with the phone before going to school, but the flowers are frozen. The falling snow and the dawn of dawn, this group of photos is like a train from autumn to spring. It reminds people of their state of mind at that time. It is a diary without words. I hope everyone can feel it after reading it. The beauty of the passage of time and the stillness of nature.')
var b7 = logPic('b7','Silence (Part 7)','Chen Yuwen','The long winter in New England is like a dream, and the speed of day and night changes is even more overwhelming. This small window happens to be Facing the stairway outside my room door, I always pass by it every time I go downstairs. The room is dark, but outside the window is often the scene of afterglow lingering on the branches and leaves. Every time I pass by, I can’t help but stop and look at it for a long time. The four-square window frame I live in such a painting, and I cannot help but want to pick up my phone to freeze this peaceful and romantic moment. The pixels of the photos are not high, and they are not carefully designed. Most of them are taken in a hurry with the phone before going to school, but the flowers are frozen. The falling snow and the dawn of dawn, this group of photos is like a train from autumn to spring. It reminds people of their state of mind at that time. It is a diary without words. I hope everyone can feel it after reading it. The beauty of the passage of time and the stillness of nature.')
var b8 = logPic('b8','Silence (Part 8)','Chen Yuwen','The long winter in New England is like a dream, and the speed of day and night changes is even more overwhelming. This small window happens to be Facing the stairway outside my room door, I always pass by it every time I go downstairs. The room is dark, but outside the window is often the scene of afterglow lingering on the branches and leaves. Every time I pass by, I can’t help but stop and look at it for a long time. The four-square window frame I live in such a painting, and I cannot help but want to pick up my phone to freeze this peaceful and romantic moment. The pixels of the photos are not high, and they are not carefully designed. Most of them are taken in a hurry with the phone before going to school, but the flowers are frozen. The falling snow and the dawn of dawn, this group of photos is like a train from autumn to spring. It reminds people of their state of mind at that time. It is a diary without words. I hope everyone can feel it after reading it. The beauty of the passage of time and the stillness of nature.')
var b9 = logPic('b9','Silence (Part 9)','Chen Yuwen','The long winter in New England is like a dream, and the speed of day and night is overwhelming. This small window happens to be Facing the stairway outside my room door, I always pass by it every time I go downstairs. The room is dark, but outside the window is often the scene of afterglow lingering on the branches and leaves. Every time I pass by, I can’t help but stop and look at it for a long time. The four-square window frame I live in such a painting, and I cannot help but want to pick up my phone to freeze this peaceful and romantic moment. The pixels of the photos are not high, and they are not carefully designed. Most of them are taken in a hurry with the phone before going to school, but the flowers are frozen. The falling snow and the dawn of dawn, this group of photos is like a train from autumn to spring. It reminds people of their state of mind at that time. It is a diary without words. I hope everyone can feel it after reading it. The beauty of the passage of time and the stillness of nature.')

var c1 = logPic('c1','Fairy Tale','Ding Tianyi','Copenhagen Newport, Denmark, a fairy-tale building by the river. One of the characteristics of traditional Danish architecture is densely packed and neatly arranged windows. The windows of all houses can In a straight line, it embodies the unique regularity of Scandinavia')
var c2 = logPic('c2','Heaven and Earth','Ding Tianyi', 'Standing on the top of Shanghai overlooking the night view of the city, the last glow of sunset is in front of you, and the horizon divides the sky and the earth into two halves. Viewing through Shanghai Center window, what you can see is the lights of thousands of families in Shanghai, the window to the world.')
var c3 = logPic('c3','Dream','Li Siquan','In 2019, in a world without COVID-19, I stayed briefly in the small town of Colmar, France. To this day, I am familiar with this place My memory is not so clear, but when I flipped through the photo album, facing the fairy-tale houses in the town, the clusters of flowers, and the afterglow of the sunset reflected by the windows made me feel like a dream. For those who are now locked at home To me, life before the pandemic seemed so far away, so dreamy.')
var c4 = logPic('c4','Yang','Tao Shengkai','-')
var c5 = logPic('c5','Zhi','Tao Shengkai','-')
var c6 = logPic('c6','Renjian','Wang Wangyi','This photo about the window was taken at the Shenkeng Hotel in Songjiang District on July 18, 2021. If I remember correctly, I took the elevator there at night Strolling downstairs, when I looked up, I felt that the lights on each floor were reflected in the entire building frame, a bit of a brilliant feeling. For the definition of window, I think it is a taste and vision for the world. Through the decoration of a window, it seems that all kinds of scenes in the world are like oil paintings dotted with frames, which are more refined. ')
var c7 = logPic('c7','White Noise','Xu Junyue','The sound of the city running outside the window is the background white noise, which sets off the quietness inside the window.')
var c8 = logPic('c8','Things of mind','Xu Junyue','The key is handed over to you, come in and listen to the thoughts of this house when you are free, remember to open the window.')
var c9 = logPic('c9','Geometry','Yao Yuxiao','Taken in Taikoo Hui, Shanghai, in the early morning. Repetitive geometric figures have always been the element and theme of my photography. The small decorative windows outside the shopping mall are in order Arranged in an orderly manner, like commodities, like parts, like all living beings, like everything in the city, and like us.')

var d1 = logPic('d1','Air','Devin.Jones','Photography in the digital age is all about filters. Windows act as their own sorts of filters, throwing up a layer of unreality between you and the other side. Whether the filter is full of grit and grime or scintillating, reflecting color, there\'s something exciting about shooting a scene that\'s being distorted in real time rather than adding those changes in post-processing!')
var d2 = logPic('d2','Period','Devin.Jones','Photography in the digital age is all about filters. Windows act as their own sorts of filters, throwing up a layer of unreality between you and the other side. Whether the filter is full of grit and grime or scintillating, reflecting color, there\'s something exciting about shooting a scene that\'s being distorted in real time rather than adding those changes in post-processing!')
var d3 = logPic('d3','City','Jinhuijie','The huge on-board TVs on the buses in Macao Special Administrative Region are undoubtedly a good way to promote the city culture of Macao. Although Macao has a small population, each bus However, it is full of people. Car TV, as a window to the city, can bring more information about the city to Macau locals or first-time tourists, so that people in Macau can fall in love with Macau through the window of the city. ')
var d4 = logPic('d4','Previous life','Jinhuijie','Through the dome of Guangfulin Cultural Exhibition Hall, we seem to have stepped into the tunnel of time and space, experiencing and reading this site in Shanghai The past and present of the city.')
var d5 = logPic('d5','Once','Mao Weizhe','Shanghai Zhangyuan. Through the window, we can see the world from a different angle, or stand in one world to see another world. In Shikumen old In front of the window of the building, I felt like I was in a space-time tunnel, and I saw the scenes inside and outside the window decades ago. Those fireworks that floated in my mind and imagination, added a sense of life and a sense of story to the original dull and boring photos. From In terms of photography, the structure of the window brings more possibilities to the composition of the picture; the glass of the window can also produce different brilliance effects through refraction and reflection, and become the highlight of the photo.')
var d6 = logPic('d6','Silence','Ng Junyi','There is a brightly colored house behind the inherent silence of the window, which makes the window bright and attractive. By recording this daily and ordinary scene, I want everyone to pay more attention to the things around them, and to appreciate every moment in life')
var d7 = logPic('d7','tea','Yan Xu','In the last winter before the epidemic, no one knows what terrible things will happen in the next year, or even in the next few years. It is a nice looking thing, but I misfocused on the table. Anyway, the sun is shining on the table and it is warm, and the tea is delicious.')
var d8 = logPic('d8','Moonlight Clan','Yao Yuxiao', 'Photographed at Hongqiao Road Subway Station, Shanghai, at night. It was getting late, and "Moonlight Clan" could still be seen through the large floor-to-ceiling windows of the subway station A figure running fast. Under the light and shadow, everyone hides their names, and under the huge waves of commerce, it becomes a depressing and unnatural thing in the city window.')

var e1 = logPic('e1','porthole','Ding Tianyi','The silhouette of the ecstasy winglet of China Eastern Airlines A350 passenger plane in the sunset. The setting sun is outside the porthole of the aircraft. Through this window, you can see the beautiful scenery of the sky and the beauty of the winglet curves, a perfect combination of industrial and natural.')
var e2 = logPic('e2','Xia','Li Siquan','The viewfinder of the camera is the window for the photographer to observe the world. What I see is the sunset, the reflection of glass and the lights of thousands of houses.')
var e3 = logPic('e3','cage','Li Siquan','The giant glass screen of the aquarium is a treacherous window with beams of light and silent shouts inside.')
var e4 = logPic('e4','miniature','Liu Siyao','When I read Alice in Wonderland as a child, Alice said: "How I wish I could shut up like a telescope!" I had a strong resonance: I also often turn the binoculars upside down, and all the scenery I see becomes distant and small. Once I came to the small classroom on the sixth floor, I found that there was a cat eye on the security door, through which I could see the miniature version of the rooftop and Shanghai. Min Gaojia. It brings back many memories and reverie in me, such as the secret garden of the Queen of Hearts, such as the pocket museum in Taipei, such as the wardrobe leading to the Kingdom of Narnia. At that moment, a childhood dream was rekindled.')
var e5 = logPic('e5','WestVirginia','Liu Siyao','Almost heaven West Virginia // Blue ridge mountains Shenandoah river // Life is old there older than the trees // Younger than the mountains // Growin \' like a breeze // Country roads take me home // To the place I belong // West Virginia // Mountain momma // Take me home country roads')
var e6 = logPic('e6','Shikumen','Mao Weizhe','Shanghai Zhangyuan. Shikumen is a fusion of Chinese and Western architectural culture, and was once a residential building with old Shanghai characteristics. Mottled windows, stairs, The public kitchen brings a sense of mystery and seclusion. With the demolition of Zhangyuan, the memory of Shikumen gradually fades into the long river of history...')
var e7 = logPic('e7','Building','Li Zhewen','This picture was taken in a residential area on Zhejiang Middle Road. I have always had a strong interest in old-fashioned residential buildings. I have been visiting relatives and friends since I was a child. The current street sweeping shooting. The urban cultural landscape and life have always been one of the objects I photograph. Today’s society is changing with each passing day, and the development of the city will definitely leave some marks. Old-fashioned residential buildings and old alleys are important components of Shanghai’s residential areas Part of it plays an indispensable role in urban development. We can see skyscrapers through the "window", but we should also go and see these old guys. After all, they also record and witness the development and changes of Shanghai .')
var e8 = logPic('e8','Fan','Sun Jingqi', 'I took this photo during the last few months of World Foreign Language Middle School in 2020. Just push the window at an angle to get the view The white sail in the window. This angle needs to be unbiased and careful to see it. The image in the window looks so real, but after all, it is just an old dream. Looking at it now, the window is the past, carrying the memories from the present to the present .')
var e9 = logPic('e9','day','Jacky.Y','-')
var e10 = logPic('e10','Line','Yan Xu', 'As the third fully automatic subway line in Shanghai, the two large windows at the front of Line 15 are undoubtedly one of its hot spots. Unlike ten The headlights on the front of Line 1 and Line 15 are enough to illuminate the railroad tracks ahead, and combined with the lights in the tunnel, the road conditions ahead can be clearly seen. The classic broadcast line "Open Metro metropolitan mobile phone swiping code to take the subway”')
var e11 = logPic('e11','Baiye','Yao Yunjie','WINDOWS. BY RACHEL SHERWOOD. From this height / the sunset spans the whole world / before me: houses and trees are shadows / neon flares between them like sudden fire / the freeways run, always / strangely vacant with riderless cars empty air // the windows up here / refract the blue slate and rose light / making the hills on the horizon collide / with ideas of Sussex, piedmont / or the cold clear wind of the Abruzzi / but that is never what is out there. // At home, the lamp curls its aurora / into the corners of the room / out the windows / squares, rectangles of light / stake out a territory on the ragged lawn. // In the center of things / between the pressing of the window and air / — a small space — / there is a meeting that defines / nothing, everything.')



var dispId = sessionStorage. getItem("imgId")
// document.getElementById("picName").innerHTML = eval(dispId).name
document.getElementById("picName").innerHTML = 'Author:'
document.getElementById("picAuthor").innerHTML = eval(dispId).author
document.getElementById("picText").innerHTML = eval(dispId).text